[build]
  base = "apps/frontend"
  command = "cd ../.. && pnpm install --no-frozen-lockfile && cd apps/frontend && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"

# 移除不兼容的重定向
# Next.js处理自己的路由，不需要这个重定向 