[build]
  base = "apps/frontend"
  command = "cd ../.. && npx pnpm install --filter=frontend... && cd apps/frontend && npx pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  NETLIFY_USE_PNPM = "true"
  PNPM_VERSION = "10.6.1"

# 移除不兼容的重定向
# Next.js处理自己的路由，不需要这个重定向 

[[redirects]]
  from = "/auth/callback/*"
  to = "/auth/callback/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  force = false 

[[plugins]]
  package = "@netlify/plugin-nextjs" 