[build]
  command = "cd ../.. && pnpm install && cd apps/frontend && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  directory = ".netlify/functions"

# 使用Next.js的特定部署设置
[[plugins]]
  package = "@netlify/plugin-nextjs" 